[package]
name = "rustypo"
version = "0.1.0"
edition = "2024"
author = "Chris Dallat"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
